### PR TITLE
Skip connz test from ruby server spec

### PR DESCRIPTION
**Pull request by wallyqs**
Follow up from https://github.com/nats-io/ruby-nats/pull/94

### CODE REVIEW

**Comment by wallyqs** [comment]
Due to the [previous commit](https://github.com/nats-io/ruby-nats/commit/3f3efc6bc41cc483f2d90cb9d401ba4aa3e727d3), it can happen when a `SUB` command is already in the `@pending` buffer by the time `connection_completed` is called.

In an example like: 

```ruby
EM.run do
  EM.add_timer(1) { EM.stop }
  nats = NATS.connect
  nats.subscribe("hello") do |msg|
    puts "[Received]: #{msg}"
  end
  nats.publish("hello", "world")
end
```

The `@pending` buffer can look like this before reaching `connection_completed`: 

```
["CONNECT {\"verbose\":false,\"pedantic\":false,\"lang\":\"ruby\",\"version\":\"0.5.1\"}\r\n", "SUB hello  2\r\n"]
```

but then once `connection_completed` is called, since we're now replaying the stored subscriptions,
there can be repeated `SUB` commands flushed to the server like this:

```
["CONNECT {\"verbose\":false,\"pedantic\":false,\"lang\":\"ruby\",\"version\":\"0.5.1\"}\r\n", "SUB hello  2\r\n", "PUB hello  5\r\nworld\r\n", "SUB hello  2\r\n"]
```

In order to avoid this, think we could adopt adding sending PING after connect,
as we're doing in other clients, right now the ruby-nats client does not have that behavior when using `NATS.connect`. For example, this prevents duplicated SUB commands:

```ruby
EM.run do
  EM.add_timer(1) { EM.stop }
  nats = NATS.connect
  nats.flush do
    nats.subscribe("hello") do |msg|
      puts "[Received]: #{msg}"
    end
    nats.publish("hello", "world")
  end
end
```

Result:

```
[58811] 2016/03/04 14:18:45.762381 [TRC] 127.0.0.1:53442 - cid:10 - ->> [CONNECT {"verbose":false,"pedantic":false,"lang":"ruby","version":"0.5.1"}]
[58811] 2016/03/04 14:18:45.762413 [TRC] 127.0.0.1:53442 - cid:10 - ->> [PING]
[58811] 2016/03/04 14:18:45.762421 [TRC] 127.0.0.1:53442 - cid:10 - <<- [PONG]
[58811] 2016/03/04 14:18:45.762741 [TRC] 127.0.0.1:53442 - cid:10 - ->> [SUB hello  2]
[58811] 2016/03/04 14:18:45.762759 [TRC] 127.0.0.1:53442 - cid:10 - ->> [PUB hello  5]
[58811] 2016/03/04 14:18:45.762765 [TRC] 127.0.0.1:53442 - cid:10 - ->> MSG_PAYLOAD: [world]
[58811] 2016/03/04 14:18:45.762773 [TRC] 127.0.0.1:53442 - cid:10 - <<- [MSG hello 2 5]
```

**Comment by derekcollison** [comment]
Should SUBS ever be in pending after a connect since we will resend subs separately? Should we just strip SUBs out of pending before sending after connect?

**Comment by wallyqs** [comment]
Think we could also do that, like on `subscribe` we could check if we are not `@connected` and return instead of putting them in pending, since they would be sent once connection is established anyway.

**Comment by derekcollison** [comment]
Either one should work, but I would probably opt not to change the normal flow but once we connect and we know we have a pending array, whip through and remove all SUB entries. Probably remove PING as well.. ;)

**Comment by wallyqs** [comment]
Fixed via #97

**Pull request closed without merging**
