### PR TITLE
Added support for the Oj JSON parser.

### PR DESCRIPTION
**Pull request by ohler55**
Added support for the Oj JSON parser. I left yawl as the first choice but gave Oj a preference over the json gem. Would you mind supporting Oj?

The same 5 tests fail before and after the change. The rest pass. Same as the base.

### CODE REVIEW

**Comment by ohler55** [comment]
Must be a timing issue. On a more recent run all passed.

**Comment by derekcollison** [comment]
Going to let @wallyqs take a look.

**Comment by wallyqs** [comment]
Thanks @ohler55.  I think that maybe we should be adding a comment on what is going on with the symbol keys options, `:symbolize_names, :symbolize_keys, :symbol_keys` all refer to the same functionality of loading the keys as symbols but for different libraries: default json lib, yajl and oj respectively.

**Comment by ohler55** [comment]
Added a comment. Does it fit the bill?

**Comment by wallyqs** [comment]
Small typo on the comment though I think that works, thanks.

**Comment by ohler55** [comment]
Theres that race condition again. Would you like me to trigger another build or is it obvious to you that fixing a spelling error in a comment is not the cause?

**Comment by wallyqs** [comment]
Don't think the spelling error should have triggered it, I think we can merge this one and revise those tests before next version release.

**Comment by ohler55** [comment]
Sounds good.

**Comment by ohler55** [comment]
It's been a pleasure. Thanks.

**Pull request merged**
