### PR TITLE
Synchronized the @pending array

### PR DESCRIPTION
**Pull request by ohler55**
When sending messages at random intervals the client would crash with a complaint about line 920 trying to push (<<) on to nil. It seems a different thread was setting @pending to nil. Using a Mutex and synchronizing fixed the issue.

### CODE REVIEW

**Comment by ripienaar** [comment]
@ohler55 this is probably because you use the eventmachine based Gem in a threaded application.

Trust me on this, your life will drastically improve if you go to the https://github.com/nats-io/pure-ruby-nats gem instead if that's the case

**Comment by ohler55** [comment]
The app is a simple test driver. Single file but it does use Fibers. Those are almost like threads. Is the performance similar on the nets-pure gem?

**Comment by ripienaar** [comment]
That gem is better in every way :)

**Comment by ohler55** [comment]
ok, might as well reject the PR. I'm surprised there is no mention of the ants-pure on the ruby-nats repo. If it is broken a redirect or at least a mention would be wise.

**Comment by wallyqs** [comment]
Thanks @ripienaar @ohler yes would rather not introduce this at this point to the gem and recommend using [nats-pure](https://github.com/nats-io/pure-ruby-nats) gem for thread safe usage and JRuby support too.

**Comment by ohler55** [comment]
The nets-pure gem seems to be working. Thanks. I'd still recommend a warning or redirect to cats-pure from the ruby-nats README.

**Comment by wallyqs** [comment]
@ohler55 added a link in the README now, thanks for the feedback 👍

**Comment by ohler55** [comment]
👍

**Pull request closed without merging**
