### PR TITLE
support custom certs and keys

### PR DESCRIPTION
**Pull request by ripienaar**
This supports various SSL related options allowing the client to specify
custom keys and certs for use during TLS

Connections options can be:

    :cert_file
       the file with a TLS client cert

    :ca_file
       the file with the CA pub cert, this will be used to verity
       the server

    :private_key_file
       the private key for the certificate in :cert_file

    :verify_peer
        boolean to enable verification, on by default when a ca_file 
        is supplied

### CODE REVIEW

**Comment by ripienaar** [comment]
Do you have any feedback on this PR?

**Comment by wallyqs** [comment]
Sorry for the delay here, think we need to add tests though could add in separate in another PR. Will take a look soon.

**Comment by ripienaar** [comment]
OK, I could take a peek at tests - the method didnt have tests to begin with which is why i didnt add any :)

**Comment by wallyqs** [comment]
I know... ;) It's ok I can take a look at the spec so that this is tested before including the functionality, thanks for the contribution!

**Comment by wallyqs** [comment]
Have been looking at this one too #103 for next release, and latest eventmachine (1.2.0) includes many updates around TLS handling:
https://github.com/eventmachine/eventmachine/blob/93122901ac92066a8edadd10d96d07f7fc03a111/CHANGELOG.md#120-march-15-2016
Spec goes red for me locally at least in doing the EM version bump so wanted to address those changes before updating TLS related handling for next version bump... that being said, I could include this changeset with the added spec covering this change and make a separate release as well but investigating a bit further on what is going on there for now.

Also there is chance that maybe some day something like the functionality being provided in this PR could make it to a latest EM so thinking on not constraining the caller from tuning the TLS handling in the client either, and just passing directly to `EM#start_tls` for customizing TLS params via possibly something like:

```ruby
NATS.start({
      :max_reconnect_attempts => 3,
      :reconnect_time_wait => 2,
      :tls => {
        :ssl_version => :TLSv1_2,
        :private_key_file => './spec/configs/certs/key.pem',
        # etc... EM#start_tls options
      }
  }) do |nc|
  puts "Connected to NATS at #{nc.connected_server}"
  NATS.stop
end
```

**Comment by ripienaar** [comment]
@wallyqs thanks, yeah that seems a reasonable change in approach - like I said I don't really know EM so hard for me to see whats best, quite surprised honestly this isn't already in EM

**Comment by wallyqs** [comment]
Took a bit of time to do the upgrade but patch is now in master and will release updated gem during this week, thanks again for the contribution!
Fixed via #113

**Pull request closed without merging**
